---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # Maintain dependencies for root dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/tests/docker/centos7"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/tests/docker/centos8"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
...
